<?php

namespace AppBundle\Repository;

/**
 * CharacterTraitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterTraitRepository extends \Doctrine\ORM\EntityRepository
{
}
