<?php

namespace AppBundle\Repository;

/**
 * RankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RankRepository extends \Doctrine\ORM\EntityRepository
{
}
